# Site settings
title: JD's notebook
email: dushoff@mcmaster.ca
baseurl: "/notebook" 
url: "https://dushoff.github.io" # the base hostname & protocol for your site
twitter_username: jd_mathbio
port: 4111

# Build settings
markdown: kramdown
